defaults:
  targets:
    linux:
      - target: x86_64-unknown-linux-gnu
        arch: amd64
        runner: ubuntu-latest
      - target: aarch64-unknown-linux-gnu
        arch: arm64
        runner: ubuntu-latest
        runner_cuda: ubuntu-24.04-arm
    darwin:
      - target: x86_64-apple-darwin
        arch: amd64
        runner: macos-latest
      - target: aarch64-apple-darwin
        arch: arm64
        runner: macos-latest
    windows:
      - target: x86_64-pc-windows-msvc
        arch: amd64
        runner: windows-latest
      - target: aarch64-pc-windows-msvc
        arch: arm64
        runner: windows-latest
  feature_sets:
    linux:
      - ""
    darwin:
      - ""
    windows:
      - ""

providers:
  mrs:
    cuda:
      disabled: true  # Temporarily disabled for faster dev cycles - set to false to re-enable
      toolkit_version: "12.8"
      strategy: "split"
      variants:
        x86_64:
          - sm: 80
            features: ["cuda", "cudnn", "flash-attn"]
          - sm: 86
            features: ["cuda", "cudnn", "flash-attn"]
          - sm: 89
            features: ["cuda", "cudnn", "flash-attn"]
          - sm: 120
            features: ["cuda", "cudnn", "flash-attn"]
        aarch64:
          - sm: 87
            features: ["cuda", "cudnn"]
    targets:
      linux: []  # Temporarily disabled for faster dev cycles - restore to defaults or add entries to re-enable
      windows: []  # Temporarily disabled for faster dev cycles - restore to defaults or add entries to re-enable
      # windows (original config - commented out for dev):
      #   - target: x86_64-pc-windows-msvc
      #     arch: amd64
      #     runner: windows-latest
      #   - target: aarch64-pc-windows-msvc
      #     arch: arm64
      #     runner: windows-latest
      #     features:
      #       - ""
    feature_sets:
      linux: []  # Temporarily disabled for faster dev cycles - restore to defaults to re-enable
      darwin:
        - "accelerate"
        # - "metal"  # Temporarily disabled for faster dev cycles - uncomment to re-enable
