defaults:
  targets:
    linux:
      - target: x86_64-unknown-linux-gnu
        arch: amd64
      - target: aarch64-unknown-linux-gnu
        arch: arm64
    darwin:
      - target: x86_64-apple-darwin
        arch: amd64
      - target: aarch64-apple-darwin
        arch: arm64
    windows:
      - target: x86_64-pc-windows-msvc
        arch: amd64
      - target: aarch64-pc-windows-msvc
        arch: arm64
  feature_sets:
    linux:
      - ""
    darwin:
      - ""
    windows:
      - ""

providers:
  mrs:
    env:
      linux:
        "cuda flash-attn cudnn":
          CUDA_COMPUTE_CAP: "86;89;120"
      windows:
        "cuda flash-attn cudnn":
          CUDA_COMPUTE_CAP: "86;89;120"
    # Per-architecture feature sets for windows (CUDA only on amd64)
    targets:
      windows:
        - target: x86_64-pc-windows-msvc
          arch: amd64
          features:
            - ""
            - "cuda flash-attn cudnn"
        - target: aarch64-pc-windows-msvc
          arch: arm64
          features:
            - ""
    feature_sets:
      linux:
        - ""
        - "cuda flash-attn cudnn"
      darwin:
        - "accelerate"
        - "metal"
