ARG PROVIDER_NAME

FROM rust:1.86-slim AS builder
ARG PROVIDER_NAME

RUN rustup target add wasm32-wasip1 && \
    rustup component add rust-std --target wasm32-wasip1 && \
    cargo install cargo-auditable

WORKDIR /workspace
COPY . .
RUN cargo fetch 
RUN cargo auditable build -p qmt-${PROVIDER_NAME} --release --target wasm32-wasip1

FROM scratch
ARG PROVIDER_NAME
WORKDIR /
COPY --from=builder /workspace/target/wasm32-wasip1/release/qmt_${PROVIDER_NAME}.wasm /plugin.wasm
