//! Core execution logic for the agent
//!
//! This module contains the main state machine loop (`execute_cycle_state_machine`)
//! used by the kameo `SessionActor` via `ctx.spawn()`. The implementation is split
//! across focused submodules:
//!
//! - `state_machine` (this file) — Main execution loop and middleware integration
//! - `transitions` — State transition functions (BeforeLlmCall, CallLlm, AfterLlm, ProcessingToolCalls)
//! - `tool_calls` — Tool execution, permission checking, and result storage
//! - `wait` — Event waiting and delegation completion handling
//! - `llm_retry` — LLM retry logic with rate limit handling
//! - `maintenance` — Pruning and AI compaction

const MAX_STOP_HOOK_CONTINUATIONS_PER_TURN: u8 = 1;

fn format_stop_hook_continuation_message(
    reason: Option<String>,
    additional_contexts: &[String],
) -> String {
    let mut message =
        String::from("<system-reminder>\nA QueryMT Stop hook requested another agent step.\n");

    if let Some(reason) = reason.filter(|reason| !reason.trim().is_empty()) {
        message.push_str("\nReason:\n");
        message.push_str(&reason);
        message.push('\n');
    }

    if !additional_contexts.is_empty() {
        message.push_str("\nAdditional hook context:\n");
        for context in additional_contexts {
            message.push_str("- ");
            message.push_str(context);
            message.push('\n');
        }
    }

    message.push_str(
        "\nThis message was generated by the QueryMT hook runtime, not by the user.\n</system-reminder>",
    );
    message
}

mod llm_retry;
mod maintenance;
mod tool_calls;
mod transitions;
mod wait;

use crate::acp::protocol::StopReason;
use crate::agent::execution_context::ExecutionContext;
use crate::agent::utils::u32_from_usize;
use crate::events::{AgentEventKind, ExecutionMetrics, StopType};
use crate::hooks::StopRequest;
use crate::middleware::ExecutionState;
use log::{debug, info, trace, warn};
use querymt::chat::ChatRole;
use std::sync::Arc;
use tracing::{Instrument, info_span, instrument};

/// Outcome of a single execution cycle
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CycleOutcome {
    Completed,
    Cancelled,
    Stopped(StopReason),
}

fn render_objective_anchor(exec_ctx: &ExecutionContext) -> String {
    let mut sections = vec![format!(
        "Original requested outcome:\n{}",
        crate::agent::utils::render_prompt_for_llm(&exec_ctx.initial_prompt, Some(16 * 1024))
    )];
    if let Some(task) = &exec_ctx.state.active_task {
        if let Some(deliverable) = &task.expected_deliverable {
            sections.push(format!("Active task deliverable: {deliverable}"));
        }
        if let Some(criteria) = &task.acceptance_criteria {
            sections.push(format!("Acceptance criteria: {criteria}"));
        }
    }
    if let Some(intent) = &exec_ctx.state.current_intent {
        sections.push(format!("Current intent: {}", intent.summary));
        if let Some(constraints) = &intent.constraints {
            sections.push(format!("Constraints: {constraints}"));
        }
    }
    if !exec_ctx.steering_summaries.is_empty() {
        sections.push(format!(
            "Latest steering (highest priority):\n{}",
            exec_ctx.steering_summaries.join("\n")
        ));
    }
    sections.push(
        "Stay within this scope. Finish once sufficient evidence exists. Ask the user rather than silently replacing the objective."
            .to_string(),
    );
    format!("[Active objective]\n{}", sections.join("\n\n"))
}

fn refresh_objective_fragment(
    context: &Arc<crate::middleware::ConversationContext>,
    exec_ctx: &ExecutionContext,
) -> Arc<crate::middleware::ConversationContext> {
    Arc::new(context.upsert_fragment(
        "active_objective",
        render_objective_anchor(exec_ctx),
        crate::middleware::ContextPriority::High,
    ))
}

async fn apply_pending_steering(
    config: &AgentConfig,
    exec_ctx: &mut ExecutionContext,
    context: &Arc<crate::middleware::ConversationContext>,
    boundary: &'static str,
    closing: bool,
) -> Result<Option<Arc<crate::middleware::ConversationContext>>, anyhow::Error> {
    let Some(inbox) = exec_ctx.steering.clone() else {
        return Ok(None);
    };
    let pending = if closing {
        inbox.begin_closing_and_drain().await
    } else {
        inbox.drain().await
    };
    if pending.is_empty() {
        return Ok(None);
    }

    let mut messages = context.messages.to_vec();
    for input in pending {
        let display = crate::agent::utils::render_prompt_for_display(&input.blocks);
        let message = crate::model::AgentMessage {
            id: uuid::Uuid::new_v4().to_string(),
            session_id: exec_ctx.session_id.clone(),
            role: querymt::chat::ChatRole::User,
            parts: vec![crate::model::MessagePart::Steering {
                run_id: exec_ctx.turn_id().unwrap_or_default().to_string(),
                client_input_id: input.client_input_id.clone(),
                blocks: input.blocks,
            }],
            created_at: time::OffsetDateTime::now_utc().unix_timestamp(),
            parent_message_id: None,
            source_provider: None,
            source_model: None,
        };
        exec_ctx.add_message(message.clone()).await?;
        messages.push(message.to_chat_message());
        if !display.trim().is_empty() {
            exec_ctx.steering_summaries.push(display);
            if exec_ctx.steering_summaries.len() > 2 {
                exec_ctx.steering_summaries.remove(0);
            }
        }
        config.emit_event(
            &exec_ctx.session_id,
            AgentEventKind::SteeringApplied {
                run_id: exec_ctx.turn_id().unwrap_or_default().to_string(),
                input_id: input.input_id,
                boundary: boundary.to_string(),
                latency_ms: crate::agent::turn_control::now_ms()
                    .saturating_sub(input.accepted_at_ms),
            },
        );
    }

    let next = crate::middleware::ConversationContext::new(
        context.session_id.clone(),
        Arc::from(messages.into_boxed_slice()),
        context.stats.clone(),
        context.provider.clone(),
        context.model.clone(),
    )
    .with_session_mode(context.session_mode)
    .with_fragments(context.fragments.clone());
    Ok(Some(Arc::new(next)))
}

// ══════════════════════════════════════════════════════════════════════════
//  State machine implementation
// ══════════════════════════════════════════════════════════════════════════

use crate::acp::client_bridge::ClientBridgeSender;
use crate::agent::agent_config::AgentConfig;

/// Execute the cycle state machine using an `AgentConfig`.
///
/// This is the entry point for the kameo `SessionActor`'s `ctx.spawn()` task.
/// It reads configuration from `AgentConfig` rather than requiring a full agent instance.
///
/// `session_mode` is the per-session `AgentMode` captured at turn start.
/// It is injected into every `ConversationContext` so middleware can read it.
#[instrument(
    name = "agent.execution.turn",
    skip(config, exec_ctx, bridge),
    fields(session_id = %exec_ctx.session_id, mode = %session_mode)
)]
pub(crate) async fn execute_cycle_state_machine(
    config: &AgentConfig,
    exec_ctx: &mut ExecutionContext,
    bridge: Option<ClientBridgeSender>,
    session_mode: crate::agent::core::AgentMode,
) -> Result<CycleOutcome, anyhow::Error> {
    debug!(
        "Starting state machine execution (free fn) for session: {}",
        exec_ctx.session_id
    );

    let driver = config.create_driver();

    debug!(
        "Session {}: state machine loading history, cancelled={}",
        exec_ctx.session_id,
        exec_ctx.cancellation_token.is_cancelled()
    );

    let messages: Arc<[querymt::chat::ChatMessage]> = async {
        let started = std::time::Instant::now();
        let messages: Arc<[querymt::chat::ChatMessage]> =
            Arc::from(exec_ctx.session_handle.history().await.into_boxed_slice());
        let elapsed_ms = started.elapsed().as_millis() as u64;
        let span = tracing::Span::current();
        span.record("history_ms", elapsed_ms);
        span.record("message_count", messages.len() as u64);
        messages
    }
    .instrument(info_span!(
        "agent.execution.history_load",
        session_id = %exec_ctx.session_id,
        history_ms = tracing::field::Empty,
        message_count = tracing::field::Empty
    ))
    .await;

    debug!(
        "Session {}: history loaded, {} messages",
        exec_ctx.session_id,
        messages.len()
    );
    let turns = messages
        .iter()
        .filter(|msg| matches!(msg.role, ChatRole::User))
        .filter(|msg| !msg.has_tool_result())
        .count();
    let stats = crate::middleware::AgentStats {
        turns,
        ..Default::default()
    };
    let stats = Arc::new(stats);

    let llm_config = exec_ctx
        .llm_config()
        .ok_or_else(|| anyhow::anyhow!("No LLM config for session"))?;

    debug!(
        "Session {}: llm_config provider={} model={}",
        exec_ctx.session_id, llm_config.provider, llm_config.model
    );

    let initial_context = Arc::new(
        crate::middleware::ConversationContext::new(
            exec_ctx.session_id.as_str().into(),
            messages,
            stats,
            llm_config.provider.as_str().into(),
            llm_config.model.as_str().into(),
        )
        .with_session_mode(session_mode),
    );

    let mut state = ExecutionState::BeforeLlmCall {
        context: initial_context.clone(),
    };
    let mut event_rx = config.event_sink.fanout().subscribe();
    let mut stop_hook_continuations = 0u8;
    let mut last_objective_checkpoint_step = 0usize;

    state = driver
        .run_turn_start(state, Some(&exec_ctx.runtime))
        .instrument(info_span!(
            "agent.execution.middleware.turn_start",
            session_id = %exec_ctx.session_id
        ))
        .await
        .map_err(|e| anyhow::anyhow!("Middleware error: {}", e))?;

    debug!(
        "Session {}: run_turn_start done, state={}, cancelled={}",
        exec_ctx.session_id,
        state.name(),
        exec_ctx.cancellation_token.is_cancelled()
    );

    loop {
        if exec_ctx.cancellation_token.is_cancelled() {
            info!("Session {}: CANCELLED at loop top", exec_ctx.session_id);
            return Ok(CycleOutcome::Cancelled);
        }

        let state_name = state.name();
        trace!(
            "State machine iteration: {} for session {}",
            state_name, exec_ctx.session_id
        );

        state = match state {
            ExecutionState::BeforeLlmCall { context } => {
                exec_ctx.report_phase(crate::agent::turn_control::RunPhase::Model);
                let context = apply_pending_steering(
                    config,
                    exec_ctx,
                    &context,
                    "before_model_request",
                    false,
                )
                .await?
                .unwrap_or(context);
                let mut context = refresh_objective_fragment(&context, exec_ctx);
                let steps = context.stats.steps;
                let checkpoint_due = (steps >= 7 && last_objective_checkpoint_step == 0)
                    || (last_objective_checkpoint_step > 0
                        && steps.saturating_sub(last_objective_checkpoint_step) >= 4);
                if checkpoint_due {
                    last_objective_checkpoint_step = steps;
                    context = Arc::new(context.upsert_fragment(
                        "objective_checkpoint",
                        "Re-evaluate the active objective before taking more actions. If the gathered evidence is sufficient, answer now. Otherwise identify exactly one missing fact and take only the action needed to resolve it. Do not expand scope without explaining why it is required.".to_string(),
                        crate::middleware::ContextPriority::High,
                    ));
                    config.emit_event(
                        &exec_ctx.session_id,
                        AgentEventKind::ObjectiveCheckpoint {
                            run_id: exec_ctx.turn_id().unwrap_or_default().to_string(),
                            reason: "exploration_budget".to_string(),
                            action: "refocus".to_string(),
                        },
                    );
                } else if last_objective_checkpoint_step > 0
                    && steps > last_objective_checkpoint_step
                {
                    context = Arc::new(context.remove_fragment("objective_checkpoint"));
                }
                let state = ExecutionState::BeforeLlmCall { context };
                let state = driver
                    .run_step_start(state, Some(&exec_ctx.runtime))
                    .instrument(info_span!(
                        "agent.execution.middleware.step_start",
                        session_id = %exec_ctx.session_id
                    ))
                    .await
                    .map_err(|e| anyhow::anyhow!("Middleware error: {}", e))?;

                match state {
                    ExecutionState::BeforeLlmCall {
                        context: ref conv_context,
                    } => {
                        transitions::transition_before_llm_call(config, conv_context, exec_ctx)
                            .await?
                    }
                    other => other,
                }
            }

            ExecutionState::CallLlm {
                ref context,
                ref tools,
            } => transitions::transition_call_llm(config, context, tools, exec_ctx).await?,

            ExecutionState::AfterLlm { .. } => {
                let state = driver
                    .run_after_llm(state, Some(&exec_ctx.runtime))
                    .instrument(info_span!(
                        "agent.execution.middleware.after_llm",
                        session_id = %exec_ctx.session_id
                    ))
                    .await
                    .map_err(|e| anyhow::anyhow!("Middleware error: {}", e))?;
                match state {
                    ExecutionState::AfterLlm {
                        ref response,
                        ref context,
                    } => {
                        transitions::transition_after_llm(config, response, context, exec_ctx)
                            .await?
                    }
                    other => other,
                }
            }

            ExecutionState::ProcessingToolCalls {
                remaining_calls,
                results,
                context,
            } => {
                exec_ctx.report_phase(crate::agent::turn_control::RunPhase::Tools);
                if results.is_empty()
                    && let Some(steered_context) = apply_pending_steering(
                        config,
                        exec_ctx,
                        &context,
                        "before_tool_batch",
                        false,
                    )
                    .await?
                {
                    let skipped = remaining_calls
                        .iter()
                        .map(|call| {
                            crate::middleware::ToolResult::new(
                                call.id.clone(),
                                vec![querymt::chat::Content::text(
                                    "Skipped because new user steering was received",
                                )],
                                true,
                                Some(call.function.name.clone()),
                                Some(call.function.arguments.clone()),
                            )
                        })
                        .collect::<Vec<_>>();
                    let next = transitions::transition_processing_tool_calls(
                        config,
                        &Arc::from(Vec::new().into_boxed_slice()),
                        &Arc::from(skipped.into_boxed_slice()),
                        &steered_context,
                        exec_ctx,
                        bridge.as_ref(),
                    )
                    .await?;
                    state = next;
                    continue;
                }
                let state = ExecutionState::ProcessingToolCalls {
                    remaining_calls,
                    results,
                    context,
                };
                let state = driver
                    .run_processing_tool_calls(state, Some(&exec_ctx.runtime))
                    .instrument(info_span!(
                        "agent.execution.middleware.processing_tool_calls",
                        session_id = %exec_ctx.session_id
                    ))
                    .await
                    .map_err(|e| anyhow::anyhow!("Middleware error: {}", e))?;
                match state {
                    ExecutionState::ProcessingToolCalls {
                        ref remaining_calls,
                        ref results,
                        ref context,
                    } => {
                        transitions::transition_processing_tool_calls(
                            config,
                            remaining_calls,
                            results,
                            context,
                            exec_ctx,
                            bridge.as_ref(),
                        )
                        .await?
                    }
                    other => other,
                }
            }

            ExecutionState::WaitingForEvent {
                ref context,
                ref wait,
            } => {
                exec_ctx.report_phase(crate::agent::turn_control::RunPhase::Waiting);
                wait::transition_waiting_for_event(config, wait, context, exec_ctx, &mut event_rx)
                    .await?
            }

            ExecutionState::Complete => {
                exec_ctx.report_phase(crate::agent::turn_control::RunPhase::Closing);
                let history = Arc::from(exec_ctx.session_handle.history().await.into_boxed_slice());
                let fallback_context = Arc::new(
                    crate::middleware::ConversationContext::new(
                        initial_context.session_id.clone(),
                        history,
                        initial_context.stats.clone(),
                        initial_context.provider.clone(),
                        initial_context.model.clone(),
                    )
                    .with_session_mode(initial_context.session_mode)
                    .with_fragments(initial_context.fragments.clone()),
                );
                if let Some(context) = apply_pending_steering(
                    config,
                    exec_ctx,
                    &fallback_context,
                    "before_completion",
                    true,
                )
                .await?
                {
                    state = ExecutionState::BeforeLlmCall { context };
                    continue;
                }
                let turn_end_state = driver
                    .run_turn_end(ExecutionState::Complete, Some(&exec_ctx.runtime))
                    .instrument(info_span!(
                        "agent.execution.middleware.turn_end",
                        session_id = %exec_ctx.session_id
                    ))
                    .await
                    .map_err(|e| anyhow::anyhow!("Middleware error: {}", e))?;

                match turn_end_state {
                    ExecutionState::BeforeLlmCall { .. } => turn_end_state,
                    ExecutionState::Complete => {
                        debug!("State machine reached Complete state");

                        let stop_hook = config
                            .hooks
                            .run_stop(StopRequest {
                                session_id: exec_ctx.session_id.clone(),
                                turn_id: exec_ctx.turn_id().unwrap_or_default().to_string(),
                                cwd: exec_ctx.cwd().map(|path| path.to_path_buf()),
                                model: exec_ctx
                                    .llm_config()
                                    .map(|cfg| cfg.model.clone())
                                    .unwrap_or_default(),
                                permission_mode: exec_ctx.permission_mode().to_string(),
                                stop_reason: "EndTurn".to_string(),
                            })
                            .await?;
                        for notice in stop_hook.notices {
                            config.emit_event(
                                &exec_ctx.session_id,
                                AgentEventKind::HookNotice {
                                    event_name: notice.event_name,
                                    message: notice.message,
                                    is_error: notice.is_error,
                                },
                            );
                        }
                        if stop_hook.should_continue {
                            if stop_hook_continuations >= MAX_STOP_HOOK_CONTINUATIONS_PER_TURN {
                                warn!(
                                    "Session {}: stop hook requested more than {} continuation(s); ignoring",
                                    exec_ctx.session_id, MAX_STOP_HOOK_CONTINUATIONS_PER_TURN
                                );
                            } else {
                                stop_hook_continuations += 1;
                                let current_context = state
                                    .context()
                                    .cloned()
                                    .unwrap_or_else(|| initial_context.clone());
                                let message = format_stop_hook_continuation_message(
                                    stop_hook.stop_reason.or(stop_hook.block_reason),
                                    &stop_hook.additional_contexts,
                                );
                                state = ExecutionState::BeforeLlmCall {
                                    context: Arc::new(current_context.inject_message(message)),
                                };
                                continue;
                            }
                        }

                        if config.execution_policy.pruning.enabled
                            && let Err(e) = maintenance::run_pruning(config, exec_ctx).await
                        {
                            warn!("Pruning failed: {}", e);
                        }

                        return Ok(CycleOutcome::Completed);
                    }
                    ExecutionState::Stopped {
                        ref message,
                        stop_type,
                        ..
                    } => {
                        info!("Turn-end middleware stopped: {} ({:?})", message, stop_type);
                        turn_end_state
                    }
                    other => other,
                }
            }

            ExecutionState::Stopped {
                ref message,
                stop_type,
                ..
            } => {
                info!("State machine stopped: {} ({:?})", message, stop_type);

                if stop_type == StopType::ContextThreshold
                    && config.execution_policy.compaction.auto
                {
                    info!("Context threshold reached, triggering AI compaction");

                    match maintenance::run_ai_compaction(config, exec_ctx, &state).await {
                        Ok(new_state) => {
                            state = new_state;
                            continue;
                        }
                        Err(e) => {
                            warn!("AI compaction failed: {}", e);
                        }
                    }
                }

                let metrics = state
                    .context()
                    .map(|ctx| ExecutionMetrics {
                        steps: u32_from_usize(
                            ctx.stats.steps,
                            "ctx.stats.steps",
                            Some(&exec_ctx.session_id),
                        ),
                        turns: u32_from_usize(
                            ctx.stats.turns,
                            "ctx.stats.turns",
                            Some(&exec_ctx.session_id),
                        ),
                    })
                    .unwrap_or_default();

                config.emit_event(
                    &exec_ctx.session_id,
                    AgentEventKind::MiddlewareStopped {
                        stop_type,
                        reason: message.to_string(),
                        metrics,
                    },
                );

                return Ok(CycleOutcome::Stopped(StopReason::from(stop_type)));
            }

            ExecutionState::Cancelled => {
                debug!("State machine cancelled");
                return Ok(CycleOutcome::Cancelled);
            }
        };
    }
}

#[cfg(test)]
mod tests {
    use super::format_stop_hook_continuation_message;

    #[test]
    fn stop_hook_continuation_message_is_labeled() {
        let message = format_stop_hook_continuation_message(
            Some("Need verification".to_string()),
            &["Run tests first".to_string()],
        );

        assert!(message.contains("<system-reminder>"));
        assert!(message.contains("A QueryMT Stop hook requested another agent step."));
        assert!(message.contains("Need verification"));
        assert!(message.contains("Run tests first"));
        assert!(message.contains("not by the user"));
    }
}

// ── Transitions moved to transitions.rs ──────────────────────────────────

// ── Tool execution moved to tool_calls.rs ────────────────────────────────

// ── Transition: WaitingForEvent moved to wait.rs ─────────────────────────

// ── LLM retry logic moved to llm_retry.rs ────────────────────────────────

// ── Pruning and AI compaction moved to maintenance.rs ────────────────────
