name: Release qmt Executable

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  APP_NAME: qmt

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ─── Linux ─────────────────────────────────────────────────────────
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_name: qmt
            archive_ext: tar.gz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin_name: qmt
            archive_ext: tar.gz

          # ─── macOS ─────────────────────────────────────────────────────────
          - os: macos-14
            target: x86_64-apple-darwin
            bin_name: qmt
            archive_ext: tar.gz
          - os: macos-14
            target: aarch64-apple-darwin
            bin_name: qmt
            archive_ext: tar.gz

          # ─── Windows ────────────────────────────────────────────────────────
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_name: qmt.exe
            archive_ext: zip
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            bin_name: qmt.exe
            archive_ext: zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain & targets
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install & cache `cross` for AArch64
        if: runner.os == 'Linux' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cargo install cross --locked --force

      - name: Build with cross
        if: ${{ runner.os == 'Linux' && matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: cross build --release --bin ${{ env.APP_NAME }} --target ${{ matrix.target }}

      - name: Build natively
        if: ${{ runner.os != 'Linux' || matrix.target != 'aarch64-unknown-linux-gnu' }}
        run: cargo build --release --bin ${{ env.APP_NAME }} --target ${{ matrix.target }}

      - name: Prepare artifact for upload
        shell: bash
        run: |
          ARTIFACT_DIR="dist"
          PKG="${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.target }}"
          STAGING="$ARTIFACT_DIR/$PKG"
          mkdir -p "$STAGING"

          cp "target/${{ matrix.target }}/release/${{ matrix.bin_name }}" "$STAGING/"
          cp README.md LICENSE "$STAGING/"

          if [[ "${{ matrix.archive_ext }}" == "zip" ]]; then
            (cd "$STAGING" && zip -r "../${PKG}.zip" .)
          else
            tar -czf "$ARTIFACT_DIR/${PKG}.tar.gz" -C "$ARTIFACT_DIR" "$PKG"
          fi

          echo "ASSET_PATH=$ARTIFACT_DIR/${PKG}.${{ matrix.archive_ext }}" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.target }}
          path: ${{ env.ASSET_PATH }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: ${{ env.APP_NAME }}-*
          merge-multiple: true

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
          draft: ${{ github.ref_type != 'tag' }}
          prerelease: ${{ github.ref_type != 'tag' }}
